(() => {
  "use strict";

  // 단어 + 한국어 힌트 (뜻·카테고리) — 힌트 보고 맞추는 데일리 워들
  const BANK = [
    ["PEACH", "과일 · 복숭아"],
    ["CANDY", "달콤한 사탕"],
    ["JELLY", "말랑한 젤리"],
    ["BUNNY", "귀여운 토끼"],
    ["KITTY", "아기 고양이"],
    ["CLOUD", "하늘에 떠 있는 구름"],
    ["SPARK", "반짝이는 불꽃·스파크"],
    ["SUGAR", "달콤한 설탕"],
    ["HONEY", "벌꿀"],
    ["BERRY", "베리류 과일"],
    ["LEMON", "신맛 나는 레몬"],
    ["MANGO", "열대과일 · 망고"],
    ["GRAPE", "포도"],
    ["MELON", "수박·멜론 계열"],
    ["COCOA", "초콜릿의 원료 · 코코아"],
    ["CREAM", "부드러운 크림"],
    ["FROST", "서리 · 차가운 얼음꽃"],
    ["FLUFF", "푹신푹신한 솜털"],
    ["SHINE", "반짝반짝 빛나다"],
    ["MAGIC", "마법"],
    ["FAIRY", "요정"],
    ["DREAM", "꿈"],
    ["SMILE", "미소 · 웃는 얼굴"],
    ["HAPPY", "행복한"],
    ["HEART", "하트 · 마음"],
    ["ANGEL", "천사"],
    ["CHICK", "병아리"],
    ["PANDA", "판다"],
    ["KOALA", "코알라"],
    ["LLAMA", "라마 (동물)"],
    ["OTTER", "수달"],
    ["WHALE", "고래"],
    ["SHELL", "조개껍데기"],
    ["PEARL", "진주"],
    ["CORAL", "산호"],
    ["OCEAN", "바다 · 대양"],
    ["RIVER", "강"],
    ["BLOOM", "꽃이 피다"],
    ["TULIP", "튤립 꽃"],
    ["DAISY", "데이지 꽃"],
    ["PETAL", "꽃잎"],
    ["GUMMY", "젤리처럼 말랑한"],
    ["DONUT", "도넛"],
    ["BAGEL", "베이글"],
    ["PIZZA", "피자"],
    ["SUSHI", "초밥"],
    ["RAMEN", "라면"],
    ["CURRY", "카레"],
    ["SALAD", "샐러드"],
    ["MUSIC", "음악"],
    ["PIANO", "피아노"],
    ["DRUMS", "드럼"],
    ["BEATS", "비트 · 리듬"],
    ["TEMPO", "음악의 빠르기"],
    ["SONGS", "노래들"],
    ["DANCE", "춤"],
    ["PARTY", "파티"],
    ["DISCO", "디스코"],
    ["PIXEL", "픽셀 · 점 하나"],
    ["RETRO", "옛날 감성 · 레트로"],
    ["LEVEL", "게임 스테이지 · 레벨"],
    ["SCORE", "점수"],
    ["BONUS", "보너스"],
    ["POWER", "파워 · 힘"],
    ["COMBO", "콤보"],
    ["PLUSH", "봉제 인형"],
    ["TEDDY", "테디베어"],
    ["BLOCK", "블록"],
    ["BRICK", "벽돌"],
    ["TILES", "타일들"],
    ["MATCH", "맞추다 · 매치"],
    ["SLIDE", "미끄러지다"],
    ["SWING", "그네 · 흔들다"],
    ["CLIMB", "올라가다"],
    ["FLOAT", "둥둥 뜨다"],
    ["GLIDE", "미끄러지듯 날다"],
    ["SUNNY", "햇살 좋은"],
    ["RAINY", "비 오는"],
    ["SNOWY", "눈 내리는"],
    ["WINDY", "바람 부는"],
    ["STORM", "폭풍"],
    ["NIGHT", "밤"],
    ["CROWN", "왕관"],
    ["JEWEL", "보석"],
    ["GLOSS", "반짝이는 광택"],
    ["GLEAM", "반짝임"],
    ["FLASH", "번쩍 · 플래시"],
    ["QUEST", "퀘스트 · 모험"],
    ["SPELL", "주문 · 스펠"],
    ["CHARM", "부적 · 매력"],
    ["FABLE", "우화 · 옛날이야기"],
    ["BACON", "베이컨"],
    ["STEAK", "스테이크"],
    ["BREAD", "빵"],
    ["TOAST", "토스트"],
    ["SHAKE", "셰이크 · 흔들다"],
    ["ROBOT", "로봇"],
    ["ALIEN", "외계인"],
    ["LASER", "레이저"],
    ["ORBIT", "궤도"],
    ["COMET", "혜성"],
    ["SWEET", "달콤한"],
    ["YUMMY", "맛있는!"],
    ["TASTY", "맛있는"],
    ["CRISP", "바삭한"],
    ["JUICY", "즙이 많은"],
    ["ZESTY", "상큼한"],
    ["SPICY", "매콤한"],
    ["GAMES", "게임들"],
    ["FUNKY", "신나는 · 펑키한"],
    ["SILLY", "Silly · 장난스러운"],
    ["GOOFY", "우스꽝스러운"],
    ["DIZZY", "어지러운"],
    ["CHESS", "체스"],
    ["APPLE", "사과"],
    ["OLIVE", "올리브"],
    ["ONION", "양파"],
    ["LATTE", "라떼"],
    ["MOCHA", "모카"],
    ["FUDGE", "퍼지 캔디"],
    ["TAFFY", "태피 캔디"],
    ["MINTY", "민트 향"],
    ["ROSEY", "장미빛 · 장밋빛"],
    ["LILAC", "라일락 · 연보라"],
    ["IVORY", "상아색 · 아이보리"],
    ["AMBER", "호박색 · 앰버"],
    ["PINKY", "새끼손가락 · 핑키"],
    ["CUTIE", "귀요미"],
    ["LAUGH", "웃다"],
    ["CHEER", "응원 · 환호"],
    ["BLISS", "더없는 행복"],
    ["PEACE", "평화"],
    ["PIXIE", "작은 요정"],
    ["GHOST", "유령"],
    ["WITCH", "마녀"],
    ["RUNES", "룬 문자"],
    ["MYTHS", "신화들"],
    ["TALES", "이야기들"],
    ["FROGS", "개구리들"],
    ["DUCKS", "오리들"],
    ["BEARS", "곰들"],
    ["TIGER", "호랑이"],
    ["ZEBRA", "얼룩말"],
    ["HORSE", "말"],
    ["SHEEP", "양"],
    ["GOATS", "염소들"],
    ["MOUSE", "생쥐"],
    ["SNAIL", "달팽이"],
    ["CRABS", "게들"],
    ["SQUID", "오징어"],
    ["SHARK", "상어"],
    ["SEALS", "물개들"],
    ["BIRDS", "새들"],
    ["EAGLE", "독수리"],
    ["ROBIN", "울새 (새)"],
    ["SWANS", "백조들"],
    ["OWLET", "아기 올빼미"],
    ["FLAME", "불꽃"],
    ["BLAZE", "타오르는 불"],
    ["GLOWY", "빛나는"],
    ["LIGHT", "빛 · 빛나다"],
    ["MOONS", "달들"],
    ["PLANT", "식물"],
    ["GRASS", "풀 · 잔디"],
    ["TREES", "나무들"],
    ["LEAFY", "잎이 무성한"],
    ["ROSES", "장미들"],
  ];

  const HINTS = Object.fromEntries(BANK);
  const ANSWERS = BANK.map(([w]) => w);

  const EXTRA = [
    "ABOUT","ABOVE","ACTOR","ACUTE","ADMIT","ADOPT","ADULT","AFTER","AGAIN","AGENT",
    "AGREE","AHEAD","ALARM","ALBUM","ALERT","ALIEN","ALIGN","ALIKE","ALIVE","ALLOW",
    "ALONE","ALONG","ALTER","AMONG","ANGER","ANGLE","ANGRY","APART","APPLE","APPLY",
    "ARENA","ARGUE","ARISE","ARRAY","ARROW","ASIDE","ASSET","AUDIO","AVOID","AWAKE",
    "AWARD","AWARE","BADLY","BAKER","BASIC","BEACH","BEGAN","BEGIN","BEING","BELOW",
    "BENCH","BIRTH","BLACK","BLAME","BLANK","BLAST","BLAZE","BLEED","BLEND","BLESS",
    "BLIND","BLINK","BLOCK","BLOOD","BLOOM","BOARD","BOOST","BOUND","BRAIN","BRAND",
    "BRAVE","BREAD","BREAK","BREED","BRIEF","BRING","BROAD","BROKE","BROWN","BUILD",
    "BUILT","BUYER","CABLE","CARRY","CATCH","CAUSE","CHAIN","CHAIR","CHAOS","CHARM",
    "CHART","CHASE","CHEAP","CHECK","CHEST","CHIEF","CHILD","CHOSE","CIVIL","CLAIM",
    "CLASS","CLEAN","CLEAR","CLICK","CLIMB","CLOCK","CLOSE","CLOUD","COACH","COAST",
    "COULD","COUNT","COURT","COVER","CRAFT","CRANE","CRASH","CRAZY","CREAM","CRIME",
    "CROSS","CROWD","CROWN","CURVE","CYCLE","DAILY","DANCE","DEATH","DEBUT","DELAY",
    "DEPTH","DOING","DOUBT","DOZEN","DRAFT","DRAMA","DRAWN","DREAM","DRESS","DRILL",
    "DRINK","DRIVE","DROVE","DYING","EAGER","EARLY","EARTH","EIGHT","ELITE","EMPTY",
    "ENEMY","ENJOY","ENTER","ENTRY","EQUAL","ERROR","EVENT","EVERY","EXACT","EXIST",
    "EXTRA","FAITH","FALSE","FAULT","FIBER","FIELD","FIFTH","FIFTY","FIGHT","FINAL",
    "FIRST","FIXED","FLASH","FLOOR","FLUID","FOCUS","FORCE","FORTH","FORTY","FORUM",
    "FOUND","FRAME","FRESH","FRONT","FRUIT","FULLY","FUNNY","GIANT","GIVEN","GLASS",
    "GLOBE","GOING","GRACE","GRADE","GRAND","GRANT","GRASS","GRAVE","GREAT","GREEN",
    "GROSS","GROUP","GROWN","GUARD","GUESS","GUEST","GUIDE","HAPPY","HEART","HEAVY",
    "HORSE","HOTEL","HOUSE","HUMAN","IDEAL","IMAGE","INDEX","INNER","INPUT","ISSUE",
    "JAPAN","JOINT","JUDGE","KNOWN","LABEL","LARGE","LASER","LATER","LAUGH","LAYER",
    "LEARN","LEASE","LEAST","LEAVE","LEGAL","LEVEL","LIGHT","LIMIT","LINKS","LIVES",
    "LOCAL","LOOSE","LOWER","LUCKY","LUNCH","LYING","MAGIC","MAJOR","MAKER","MARCH",
    "MATCH","MAYBE","MAYOR","MEANT","MEDIA","METAL","MIGHT","MINOR","MINUS","MIXED",
    "MODEL","MONEY","MONTH","MORAL","MOTOR","MOUNT","MOUSE","MOUTH","MOVED","MOVIE",
    "MUSIC","NEEDS","NEVER","NEWLY","NIGHT","NOISE","NORTH","NOTED","NOVEL","NURSE",
    "OCCUR","OCEAN","OFFER","OFTEN","ORDER","OTHER","OUGHT","PAINT","PANEL","PAPER",
    "PARTY","PEACE","PHASE","PHONE","PHOTO","PIECE","PILOT","PITCH","PLACE","PLAIN",
    "PLANE","PLANT","PLATE","POINT","POUND","POWER","PRESS","PRICE","PRIDE","PRIME",
    "PRINT","PRIOR","PRIZE","PROOF","PROUD","PROVE","QUEEN","QUICK","QUIET","QUITE",
    "RADIO","RAISE","RANGE","RAPID","RATIO","REACH","READY","REFER","RIGHT","RIVAL",
    "RIVER","ROBIN","ROUGH","ROUND","ROUTE","ROYAL","RURAL","SCALE","SCENE","SCOPE",
    "SCORE","SENSE","SERVE","SEVEN","SHALL","SHAPE","SHARE","SHARP","SHEET","SHELF",
    "SHELL","SHIFT","SHINE","SHIRT","SHOCK","SHOOT","SHORT","SHOWN","SIGHT","SINCE",
    "SIXTH","SIXTY","SKILL","SLEEP","SLIDE","SMALL","SMART","SMILE","SMOKE","SOLID",
    "SOLVE","SORRY","SOUND","SOUTH","SPACE","SPARE","SPEAK","SPEED","SPEND","SPENT",
    "SPLIT","SPOKE","SPORT","STAFF","STAGE","STAKE","STAND","START","STATE","STEAM",
    "STEEL","STICK","STILL","STOCK","STONE","STOOD","STORE","STORM","STORY","STRIP",
    "STUCK","STUDY","STUFF","STYLE","SUGAR","SUITE","SUPER","SWEET","TABLE","TAKEN",
    "TASTE","TEACH","THANK","THEIR","THEME","THERE","THESE","THICK","THING","THINK",
    "THIRD","THOSE","THREE","THREW","THROW","TIGHT","TIMES","TIRED","TITLE","TODAY",
    "TOPIC","TOTAL","TOUCH","TOUGH","TOWER","TRACK","TRADE","TRAIN","TREAT","TREND",
    "TRIAL","TRIBE","TRICK","TRIED","TRIES","TRUCK","TRULY","TRUNK","TRUST","TRUTH",
    "TWICE","UNDER","UNION","UNITY","UNTIL","UPPER","UPSET","URBAN","USAGE","USUAL",
    "VALID","VALUE","VIDEO","VIRUS","VISIT","VITAL","VOCAL","VOICE","WASTE","WATCH",
    "WATER","WHEEL","WHERE","WHICH","WHILE","WHITE","WHOLE","WHOSE","WOMAN","WOMEN",
    "WORLD","WORRY","WORSE","WORST","WORTH","WOULD","WOUND","WRITE","WRONG","WROTE",
    "YOUNG","YOUTH","CHESS","CHIPS","CHOIR","CHORD","CIVIC","CLAMP","CLASH","CLASP",
    "CLERK","CLIFF","CLING","CLONE","CLOTH","CLOWN","COBRA","COCOA","CRANE","CRISP",
    "CROWN","DAISY","DIZZY","DONUT","DRUMS","EAGLE","FABLE","FAIRY","FLAME","FLUFF",
    "FROST","FUDGE","FUNKY","GLEAM","GLIDE","GLOSS","GOOFY","GRAPE","GUMMY","HONEY",
    "IVORY","JELLY","JEWEL","JUICY","KITTY","KOALA","LATTE","LEMON","LLAMA","MANGO",
    "MELON","MINTY","MOCHA","OLIVE","ONION","ORBIT","OTTER","OWLET","PANDA","PEACH",
    "PEARL","PETAL","PIANO","PIXEL","PIZZA","PLUSH","QUEST","RAMEN","RETRO","ROBOT",
    "ROSEY","SALAD","SHAKE","SHARK","SHEEP","SILLY","SNAIL","SPARK","SPELL","SPICY",
    "SQUID","STEAK","SUSHI","SWANS","TAFFY","TASTY","TEDDY","TEMPO","TIGER","TILES",
    "TOAST","TULIP","WHALE","WITCH","YUMMY","ZEBRA","ZESTY","ANGEL","AMBER",
    "BACON","BAGEL","BEARS","BEATS","BERRY","BLAZE","BLISS","BONUS","BRICK","BUNNY",
    "CANDY","CHARM","CHEER","CHICK","CLIMB","CLOUD","COMBO","COMET","CORAL","CREAM",
    "CURRY","CUTIE","DANCE","DISCO","DREAM","DUCKS","FAIRY",
    "FLASH","FLOAT","FROGS","GAMES","GHOST","GOATS","GRASS","HEART","HORSE",
    "LASER","LEAFY","LEVEL","LIGHT","MAGIC","MATCH","MOONS","MOUSE","MUSIC","MYTHS",
    "NIGHT","OCEAN","PARTY","PEACE","PINKY","PLANT","POWER","RAINY","RIVER","ROSES",
    "RUNES","SCORE","SEALS","SHELL","SHINE","SLIDE","SMILE","SNOWY","SONGS",
    "STORM","SUGAR","SUNNY","SWEET","SWING","TALES","TEMPO","TIGER",
    "TREES","WHALE","WINDY","YEAST","YOUTH","ZONAL","ZONED","ZONES","ZOOMS",
  ].map((w) => w.toUpperCase()).filter((w) => /^[A-Z]{5}$/.test(w));

  const VALID = new Set([...ANSWERS, ...EXTRA]);
  const CLEAN_ANSWERS = [...new Set(ANSWERS.filter((w) => VALID.has(w) && HINTS[w]))];
  const DAILY_LIMIT = 100;

  function seoulDay() {
    return new Date().toLocaleString("en-CA", { timeZone: "Asia/Seoul" }).slice(0, 10);
  }

  function daySeed(day) {
    let h = 2166136261;
    for (let i = 0; i < day.length; i += 1) {
      h ^= day.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return h >>> 0;
  }

  /** 날짜마다 섞인 문제 큐 (최대 100개, 중복 없음) */
  function dailyQueue(day) {
    const arr = [...CLEAN_ANSWERS];
    let s = daySeed(day) || 1;
    for (let i = arr.length - 1; i > 0; i -= 1) {
      s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
      const j = s % (i + 1);
      const tmp = arr[i];
      arr[i] = arr[j];
      arr[j] = tmp;
    }
    return arr.slice(0, Math.min(DAILY_LIMIT, arr.length));
  }

  function getPuzzle(day, puzzleIndex) {
    const queue = dailyQueue(day);
    const total = queue.length;
    const idx = Math.max(0, Math.min(puzzleIndex, total - 1));
    const word = queue[idx];
    return {
      day,
      word,
      hint: HINTS[word] || "귀여운 영어 단어",
      index: idx + 1,
      puzzleIndex: idx,
      total,
      exhausted: puzzleIndex >= total,
    };
  }

  window.WordleWords = {
    VALID,
    CLEAN_ANSWERS,
    HINTS,
    DAILY_LIMIT,
    seoulDay,
    dailyQueue,
    getPuzzle,
  };
})();
